core/urls.py
from django.contrib import admin
from django.urls import path,include

from .views import hi, r, tag_test

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hi/<int:n1>/<int:n2>/', hi),
    path('r/<int:begin>/<int:end>/', r),
    path('r/<int:begin>/<int:end>/<int:option>/', r),
    path('tag_test/', tag_test),

    path('posts/',include('practice1.urls'))
]

practice1/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('<int:pk>/', views.show, name='show')
]

practice1/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=255)

    def __str__(self):
        return self.title

core/forms.py
from django.forms import ModelForm


class BootstrapModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': '請輸入{}'.format(self.fields[field].label)
            })

practice1/forms.py
from core.forms import BootstrapModelForm
from .models import Post


class PostModelForm(BootstrapModelForm):
    class Meta:
        model = Post
        fields = '__all__'

core/views.py
from django.shortcuts import render


def hi(request, n1, n2):
    return render(request, 'hi.html', {
        's': n1 + n2
    })

def r(request, begin, end, option = None):
    if begin > end:
        rr = reversed(range(end, begin + 1))
    else:
        rr = range(begin, end + 1)
    if option == 0:
        rr = filter(lambda x : x % 2 == 0, rr)
    elif option == 1:
        rr = filter(lambda x : x % 2 == 1, rr)

    return render(request, 'r.html', {
        'rr': rr
    })

def tag_test(request):
    l = [1,2,3,4,5,6,7,8,9]
    return render(request, 'tag_test.html', {
        'l': l
    })

practice1/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostModelForm


def index(request):
    posts = Post.objects.all()
    return render(request, 'posts/index.html', {
        'posts': posts
    })


def show(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'posts/show.html', {
        'post': post
    })


# def new(request):
#     if request.method == 'POST':
#         title = request.POST.get('title')
#         content = request.POST.get('content')
#         if title == '' or content == '':
#             return render(request, 'posts/new.html',{
#                 'error':['有欄位未填寫']
#             })

#         Post.objects.create(title=title, content=content)
#         return redirect('posts_index')
#     return render(request, 'posts/new.html')

def new(request):
    form = PostModelForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('posts:index')
    return render(request, 'posts/new.html', {
        'form': form
    })


def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostModelForm(request.POST or None,instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:index')

    return render(request, 'posts/edit.html', {
        'form': form
    })


def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('posts:index')

templates/_form.html
<form action="" method="post">
    {% csrf_token %}
    
    {% if form.non_field_errors %}
        <div class="alert alert-danger" style="margin-top: 10px;">
        {% for error in form.non_field_errors %}
            <strong>{{ error }}</strong>
        {% endfor %}
        </div>
    {% endif %}
    
    {% for field in form %}
        <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">{{ field.label }}</span>
        </div>
        {{ field }}
        </div>
        {% if field.errors %}
        <div class="alert alert-dismissible alert-danger fade show" style="margin-top: 10px;">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ field.label }}錯誤</strong>
            {% for error in field.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
    {% endfor %}
    
    <button type="submit" class="btn btn-info float-right">送出</button>
</form>
    
<style>
textarea {
    resize: none;
}
</style>

templates/hi.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title> hi </title>
</head>

<body>
    <h1>{{s}}</h1>
    {% if s > 60 %}
        <p>over 60</p>
    {% endif %}
    
</body>

</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %}MyDjangoWeb{% endblock title %} </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-2">
        <div class="row">
            <div class="col">
                {% block main %} {% endblock main %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/posts/edit.html
{% extends "layout.html" %}
{% block title %}Edit Posts{% endblock title %}
{% block main %}
    <h1>Edit</h1>
    <a class="btn btn-outline-warning" href="{% url 'posts:index' %}">back</a>
    <hr>
    {% include "_form.html" %}
{% endblock main %}

templates/posts/index.html
{% extends "layout.html" %}
{% block title %}Posts{% endblock title %}
{% block main %}
    <h1>Posts</h1>
    <a class="btn btn-outline-primary" href="{% url 'posts:new' %}">New Posts</a>
    <hr>
    {% for post in posts %}
        <!-- <a href="/posts/{{post.id}}/">{{post.id}} </a> -->
        <a class="btn btn-outline-info" href="{% url 'posts:show' post.id %}">{{post.id}} </a>
        <span> | {{post.title}} - {{post.content}}</span>
        <a class="btn btn-outline-danger" href="{% url 'posts:delete' post.id %}">delete</a>
        <br>
    {% endfor %}
{% endblock main %}

templates/posts/new.html
{% extends "layout.html" %}
{% block title %}New Posts{% endblock title %}
{% block main %}
    <a class="btn btn-outline-warning" href="{% url 'posts:index' %}">back</a>
    <h1>New</h1>
    <hr>
    {% include "_form.html" %}
{% endblock main %}

templates/posts/show.html
{% extends "layout.html" %}
{% block title %}Show Posts{% endblock title %}
{% block main %}
    <h1>Show</h1>
    <a class="btn btn-outline-info" href="{% url 'posts:edit' post.id %}">edit</a>
    <span>{{post.id}} - {{post.title}} - {{post.content}}</span><br>
    <a class="btn btn-outline-warning" href="{% url 'posts:index' %}">back</a>
{% endblock main %}

templates/r.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title> r </title>
</head>

<body>
    <ul>
        {% for i in rr %}
        <li>{{i}}</li>
        {% endfor %}
    </ul>
</body>

</html>

templates/tag_test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title> r </title>
</head>

<body>
    {{l|join:"\/\/<br>"|safe}}\/\/
</body>

</html>